title:              Pixel Blog
email:              uysalaltas@gmail.com
description:        Blog about Computer Graphics and General Programming
author:             Uysal ALTAS
baseurl:            ""
url:                "uysalaltas.github.io"

# Social Profiles
twitter_username:   AltasUysal
github_username:    uysalaltas
facebook_username:
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
